Repository vmware/terraform-provider-avi, pull requests merged in 2019-09, with the labels that each got.

#7 AV-68694 Added api_timeout property to avi provider definition
  avi/provider.go
  avi/provider_test.go
  examples/basic/avi_example.tf
Labels: size/S

#8 AV-64687 Cleanup Terraform VSVIP examples
  examples/aws/avi_app/avi_config.tf
  examples/azure/avi_vs/avi_vs.tf
  examples/basic/avi_example.tf
  examples/openstack/web_app/avi_config.tf
Labels: size/M

#9 Av 67986: Provider produced inconsistent result after apply" in Terraform
  avi/resource_avi_useraccount.go
Labels: size/XS

#10 Update README.md
  README.md
Labels: size/XS
