Repository vmware/terraform-provider-avi, pull requests merged in 2020-03, with the labels that each got.

#42 AV-70462: changed provider to use lazy authentication
  avi/provider.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
  vendor/github.com/avinetworks/sdk/go/session/avisession_test.go
Labels: dependencies, size/XL

#46 updated basic terraform example to support pool group and parameteriz…
  examples/basic/avi_example.tf
  examples/basic/variables.tf
Labels: size/M

#45 Av 79347 Fixed for Unable to reconcile state of resources modified outside Terraform
  avi/resource_avi_pool_server.go
  examples/test/state_test/avi_example.tf
  examples/test/state_test/test_reconcile_state.py
  examples/test/state_test/variables.tf
Labels: size/L
