Repository vmware/terraform-provider-avi, pull requests merged in 2020-01, with the labels that each got.

#23 Create horizon_l7_l4_sharedvip_vcenter.tf
  examples/Horizon/SharedViP/horizon_l7_l4_sharedvip_vcenter.tf
Labels: size/L

#24 Create variables.tf
  Horizon/SharedViP/variables.tf
Labels: size/XS

#26 Create horizon_l4only.tf
  examples/Horizon/L4only/horizon_l4only.tf
Labels: size/L

#28 Create variables.tf
  examples/Horizon/L4only/variables.tf
Labels: size/XS

#31 AV-76349 Fixed Avi terraform enable=false is ignored.
  avi/resource_avi_virtualservice_test.go
  avi/utils.go
Labels: size/S

#27 Create terraform.tfvars
  examples/Horizon/L4only/terraform.tfvars
Labels: size/XS

#32 Revert "Create terraform.tfvars"
  examples/Horizon/L4only/terraform.tfvars
Labels: size/XS

#33 Revert "AV-76349 Fixed Avi terraform enable=false is ignored."
  avi/resource_avi_virtualservice_test.go
  avi/utils.go
Labels: size/S
