Repository vmware/terraform-provider-avi, pull requests merged in 2020-06, with the labels that each got.

#63 Added documentation for Avi Useraccount Resource
  website/avi.erb
  website/docs/r/avi_useraccount.html.markdown
Labels: documentation, size/S

#64 AV-85581 Added seproperties into post not allowed list
  avi/utils.go
Labels: size/XS

#71 Rc 18.2.9 1
  avi/resource_avi_rest_dependants.go
Labels: size/XL
