Repository vmware/terraform-provider-avi, pull requests merged in 2020-02, with the labels that each got.

#37 Rename Horizon/SharedViP/variables.tf to examples/Horizon/SharedViP/v…
  examples/Horizon/SharedViP/variables.tf
Labels: size/XS

#35 Av 76349 Avi terraform enable=false is ignored.
  avi/resource_avi_virtualservice_test.go
  avi/utils.go
Labels: size/S

#41 Av 78192 Terraform module to deploy VM on the Vcenter and configure the cluster
  avi/provider.go
  avi/provider_test.go
  examples/Vmware/Readme.md
  examples/Vmware/user_account.tf
  examples/Vmware/variables.tf
  examples/Vmware/vmware.tf
  modules/services/vmware_deploy/main.tf
  modules/services/vmware_deploy/outputs.tf
  modules/services/vmware_deploy/variables.tf
Labels: size/L
