Repository vmware/terraform-provider-avi, pull requests merged in 2020-07, with the labels that each got.

#76 website: Remove leftover files copied from `template` provider
  website/docs/d/cloudinit_config.html.markdown
  website/docs/d/file.html.md
  website/docs/r/dir.html.md
Labels: documentation, size/XL

#66 Added pool example
  examples/pool/pool_template/main.tf
  examples/pool/pool_template/test.tfvars
  examples/pool/pool_template/variables.tf
Labels: size/M

#73 AV-87850 Added vcenter cloud example
  examples/cloud/vmware/main.tf
  examples/cloud/vmware/output.tf
  examples/cloud/vmware/variables.tf
Labels: size/M

#1 Added GCP examples
  .gitignore
  examples/gcp/.gitignore
  examples/gcp/cloudCreation/main.tf
  examples/gcp/cloudCreation/terraform.tfvars
  examples/gcp/cloudCreation/variables.tf
  examples/gcp/clusterCreation/main.tf
  examples/gcp/clusterCreation/terraform.tfvars
  examples/gcp/clusterCreation/variables.tf
  examples/gcp/controllerCreation/main.tf
  examples/gcp/controllerCreation/terraform.tfvars
  examples/gcp/controllerCreation/variables.tf
  examples/gcp/customRoleCreation/main.tf
  examples/gcp/customRoleCreation/terraform.tfvars
  examples/gcp/customRoleCreation/variables.tf
Labels: size/XL
